//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asseponto.Suporte {
    
    
    public partial class _default {
        
        /// <summary>
        /// PedidosResumo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asseponto.WebControls.PedidosResumo PedidosResumo1;
        
        /// <summary>
        /// SolicitacoesResumo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asseponto.WebControls.SolicitacoesResumo SolicitacoesResumo1;
        
        /// <summary>
        /// SolicitacoesResumoRevenda control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asseponto.WebControls.SolicitacoesResumoRevenda SolicitacoesResumoRevenda;
        
        /// <summary>
        /// ImplantacoesResumo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asseponto.WebControls.ImplantacoesResumo ImplantacoesResumo1;
        
        /// <summary>
        /// UltimasEmpresas1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asseponto.WebControls.UltimasEmpresas UltimasEmpresas1;
        
        /// <summary>
        /// PendenciasResumo1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asseponto.WebControls.PendenciasResumo PendenciasResumo1;
        
        /// <summary>
        /// PendenciasResumo2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asseponto.WebControls.PendenciasResumo PendenciasResumo2;
    }
}
