USE COMGEN;
DECLARE @P_DEPTO INT = 1,
		@P_DATA DATE = '29/09/2016',
		@P_DIAS INT = 0,
		@P_PORCENTO_1 INT = 50,
		@P_PORCENTO_2 INT = 100

CREATE TABLE #dbtRelatorioBancoHoras (
FUNC INT,
--VALOR DECIMAL(5, 2),
VALOR1 DECIMAL(5, 2),
VALOR2 DECIMAL(5, 2),
DIA INT
);

IF @P_DIAS > DATEPART(DAY, DBO.FN_ULTIMO_DIA_MES(@P_DATA)) OR @P_DIAS = 0 SET @P_DIAS = DATEPART(DAY, DBO.FN_ULTIMO_DIA_MES(@P_DATA))

DECLARE @FUNC INT, @DIA INT = DATEPART(DAY, @P_DATA), @MES INT = DATEPART(MONTH, @P_DATA), 
		@ANO INT = DATEPART(YEAR, @P_DATA), @GRUPO INT, @VALOR DECIMAL (5,2), @VALOR1 DECIMAL(5, 2),
		@VALOR2 DECIMAL(5, 2), @DATAINICIAL SMALLDATETIME, @DATAFINAL SMALLDATETIME 


DECLARE funcs_cursor CURSOR FOR
		SELECT FUNC_IND FROM Funcionarios WHERE dbo.fn_departamentopertencente(FUNC_EMPRESA, @P_DEPTO) = 1

OPEN funcs_cursor

FETCH NEXT FROM funcs_cursor INTO @FUNC

WHILE @@FETCH_STATUS = 0
		BEGIN
		SET @DIA = DATEPART(DAY, @P_DATA)
		--INSERT INTO #dbtRelatorioBancoHoras (FUNC) VALUES (@FUNC)

		WHILE @DIA <= @P_DIAS
			BEGIN
			SELECT @DATAINICIAL = @P_DATA
			SELECT @DATAFINAL = CONVERT(DATE, dbo.fn_ultimo_dia_mes(@DATAINICIAL))

			SET @VALOR = NULL
			SET @VALOR1 = NULL
			SET @VALOR2 = NULL

			SELECT @VALOR1 = CONVERT(DECIMAL(5, 2), SUM(dbo.fn_hourlongtominute(BCO_VALORSEMACRESCIMO))) / 60 
			FROM BcoHoras WHERE BCO_FUNC = @FUNC AND BCO_PORCENTO = @P_PORCENTO_1 AND 
				BCO_DATA >= @DATAINICIAL AND BCO_DATA <= @DATAFINAL AND DATEPART(DAY, BCO_DATA) = @DIA
			SELECT @VALOR2 = CONVERT(DECIMAL(5, 2), SUM(dbo.fn_hourlongtominute(BCO_VALORSEMACRESCIMO))) / 60 
			FROM BcoHoras WHERE BCO_FUNC = @FUNC AND BCO_PORCENTO = @P_PORCENTO_2 AND 
				BCO_DATA >= @DATAINICIAL AND BCO_DATA <= @DATAFINAL AND DATEPART(DAY, BCO_DATA) = @DIA
				 
			INSERT INTO #dbtRelatorioBancoHoras (FUNC, VALOR1, VALOR2, DIA) 
										VALUES (@FUNC,@VALOR1,@VALOR2,@DIA)
			--UPDATE #dbtRelatorioBancoHoras SET VALOR1 = @VALOR1, VALOR2 = @VALOR2, DIA = @DIA WHERE FUNC = @FUNC
			--IF @MESC = 1 UPDATE #dbtRelatorioBancoHoras SET MES1_HE_70 = @HE_70, MES1_HE_100 = @HE_100 WHERE FUNC = @FUNC
			--IF @MESC = 2 UPDATE #dbtRelatorioBancoHoras SET MES2_HE_70 = @HE_70, MES2_HE_100 = @HE_100 WHERE FUNC = @FUNC
			--IF @MESC = 3 UPDATE #dbtRelatorioBancoHoras SET MES3_HE_70 = @HE_70, MES3_HE_100 = @HE_100 WHERE FUNC = @FUNC
			--IF @MESC = 4 UPDATE #dbtRelatorioBancoHoras SET MES4_HE_70 = @HE_70, MES4_HE_100 = @HE_100 WHERE FUNC = @FUNC
			--IF @MESC = 5 UPDATE #dbtRelatorioBancoHoras SET MES5_HE_70 = @HE_70, MES5_HE_100 = @HE_100 WHERE FUNC = @FUNC
			--IF @MESC = 6 UPDATE #dbtRelatorioBancoHoras SET MES6_HE_70 = @HE_70, MES6_HE_100 = @HE_100 WHERE FUNC = @FUNC

			--SET @MESC = @MESC + 1
			SET @DIA = @DIA + 1

			--IF @MES = 13
			--	BEGIN
			--	SET @MES = 1
			--	SET @ANO = @ANO + 1
			--	END
			END

		FETCH NEXT FROM funcs_cursor INTO @FUNC
		END

CLOSE funcs_cursor
DEALLOCATE funcs_cursor

SET @DIA = DATEPART(DAY, @P_DATA)
--SET @MES = @P_MES_INICIAL
--SET @ANO = @P_ANO_INICIAL

DECLARE @S NVARCHAR(MAX), @WHERE NVARCHAR(MAX)
SET @S = 'SELECT FUNC_REG AS REGISTRO, FUNC_NOME AS NOME, CAR_DESCRICAO AS CARGO, '
SET @WHERE = 'WHERE EXISTS(SELECT * FROM #dbtRelatorioBancoHoras WHERE FUNC = FUNC_IND) AND    '

WHILE @DIA <= @P_DIAS
		BEGIN
		SET @S = @S + '(CONVERT(VARCHAR(20), ISNULL((SELECT SUM(VALOR1) FROM #dbtRelatorioBancoHoras WHERE FUNC = FUNC_IND AND DIA = ' + 
		CONVERT(VARCHAR(MAX), @DIA) + ' ), ''0.0'')) + '' - '' + 
						CONVERT(VARCHAR(20), ISNULL((SELECT SUM(VALOR2) FROM #dbtRelatorioBancoHoras WHERE FUNC = FUNC_IND AND DIA = ' + 
		CONVERT(VARCHAR(MAX), @DIA) + ' ), ''0.0''))) AS [DIA ' + CONVERT(VARCHAR(MAX), @DIA) + ' (' + CONVERT(NVARCHAR(MAX), @P_PORCENTO_1) + '% - ' + 
		CONVERT(NVARCHAR(MAX), @P_PORCENTO_2) + '%)], '
		--SET @S = @S + '(SELECT SUM(VALOR2) FROM #dbtRelatorioBancoHoras WHERE FUNC = FUNC_IND AND DIA = ' + 
		--CONVERT(VARCHAR(MAX), @DIA) + ' ) AS [DIA ' + CONVERT(VARCHAR(MAX), @DIA) + '-' + CONVERT(NVARCHAR(MAX), @P_PORCENTO_2) + '%], '
				
		--SET @WHERE = @WHERE + '1 = 1 OR '
		--SET @WHERE = @WHERE + 'VALOR1 IS NOT NULL OR '
		--SET @WHERE = @WHERE + 'VALOR2 IS NOT NULL AND '
		--SET @WHERE = @WHERE + 'DIA = ' + CONVERT(VARCHAR(MAX), @DIA) + 'OR '

		SET @DIA = @DIA + 1
		--SET @MES = @MES + 1

		--IF @MES = 13
				--BEGIN
				--SET @MES = 1
				--SET @ANO = @ANO + 1
				--END
		END

SET @S = SUBSTRING(@S, 1, LEN(@S) - 1)
SET @WHERE = SUBSTRING(@WHERE, 1, LEN(@WHERE) - 3)
	
--SET @S = @S + ' FROM #dbtRelatorioBancoHoras INNER JOIN Funcionarios ON FUNC_IND = FUNC LEFT JOIN Cargos ON CAR_IND = FUNC_CARGO ' 
SET @S = @S + ' FROM Funcionarios LEFT JOIN Cargos ON CAR_IND = FUNC_CARGO ' 
SET @S = @S + @WHERE
SET @S = @S + ' ORDER BY FUNC_NOME'
PRINT @S
EXEC(@S)

--SELECT * FROM #dbtRelatorioBancoHoras
--DROP TABLE #dbtRelatorioBancoHoras
--SELECT FUNC_REG AS REGISTRO, 
--	   FUNC_NOME AS NOME, 
--	   CAR_DESCRICAO AS CARGO, 
--	   (CONVERT(VARCHAR(20), ISNULL((SELECT SUM(VALOR1) FROM #dbtRelatorioBancoHoras WHERE FUNC = FUNC_IND AND DIA = 29 ), '0.0')) + ' - ' + 
--	   CONVERT(VARCHAR(20), ISNULL((SELECT SUM(VALOR2)
--						     FROM #dbtRelatorioBancoHoras 
--						     WHERE FUNC = FUNC_IND AND DIA = 29 ), '0.0'))) AS [DIA 29 (50% - 100%)], 
--	   (CONVERT(VARCHAR(20), ISNULL((SELECT SUM(VALOR1) 
--							 FROM #dbtRelatorioBancoHoras 
--							 WHERE FUNC = FUNC_IND AND DIA = 30 ), '0.0')) + ' - ' + 
--	   CONVERT(VARCHAR(20), ISNULL((SELECT SUM(VALOR2) 
--							 FROM #dbtRelatorioBancoHoras 
--							 WHERE FUNC = FUNC_IND AND DIA = 30 ), '0.0'))) AS [DIA 30 (50% - 100%)] 
--FROM Funcionarios 
--LEFT JOIN Cargos ON CAR_IND = FUNC_CARGO 
--WHERE EXISTS(SELECT * FROM #dbtRelatorioBancoHoras WHERE FUNC = FUNC_IND) 
--ORDER BY FUNC_NOME
--SELECT FUNC_IND FROM Funcionarios WHERE dbo.fn_departamentopertencente(FUNC_EMPRESA, 1) = 1