USE comgen;
GO
--EXEC rst_banco_horas_horas_extras_porcentagemTESTE
--@P_DEPTO = 1, 
--@P_MES_INICIAL = 8, 
--@P_ANO_INICIAL = 2016, 
--@P_MESES = 6, 
--@P_PORCENTO_1 = 50,
--@P_PORCENTO_2 = 100

EXEC rst_banco_horas_horas_extras_porcentagemTESTE1
@P_DEPTO = 1, 
@P_DATA = '01/09/2016',
@P_DIAS = 0,
@P_PORCENTO_1 = 50,
@P_PORCENTO_2 = 100

--SELECT  *
--FROM BcoHoras WHERE BCO_FUNC = 49 AND BCO_PORCENTO = 50 AND 
--	 BCO_DATA >= '01/09/2016' AND BCO_DATA <= '30/09/2016' AND DATEPART(DAY, BCO_DATA) = 29
--SELECT CONVERT(DECIMAL(5, 2), SUM(dbo.fn_hourlongtominute(BCO_VALORSEMACRESCIMO))) / 60 
--FROM BcoHoras WHERE BCO_FUNC = 49 AND BCO_PORCENTO = 50 AND 
--	 BCO_DATA >= '15/09/2016' AND BCO_DATA <= '30/09/2016' AND DATEPART(DAY, BCO_DATA) = 26

--SELECT * FROM Empresas
--SELECT * FROM comgen.DBO.BcoHoras WHERE BCO_VALORSEMACRESCIMO IS NOT NULL
--SELECT * FROM fUNCIONARIOS